In [83]:
from sklearn.datasets import load_iris
iris = load_iris()
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [84]:
iris.data[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [85]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(iris.data)
iris_data = scaler.transform(iris.data)
print(iris_data[:10])

[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]
 [-0.53717756  1.93979142 -1.16971425 -1.05217993]
 [-1.50652052  0.78880759 -1.34022653 -1.18381211]
 [-1.02184904  0.78880759 -1.2833891  -1.3154443 ]
 [-1.74885626 -0.36217625 -1.34022653 -1.3154443 ]
 [-1.14301691  0.09821729 -1.2833891  -1.44707648]]


In [86]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    iris.data, 
    iris.target, 
    random_state=42, 
    stratify=iris.target, 
    test_size=0.3
)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(105, 4) (105,)
(45, 4) (45,)


In [87]:
import numpy as np
np.unique(y_test, return_counts=True)

(array([0, 1, 2]), array([15, 15, 15]))

In [88]:
from sklearn.neighbors import KNeighborsClassifier
iris_knn = KNeighborsClassifier()
iris_knn.fit(X_train, y_train)
pred = iris_knn.predict(X_test)
print(pred)


[2 1 2 1 2 2 1 1 0 2 0 0 2 2 0 2 1 0 0 0 1 0 1 2 2 1 1 1 1 0 2 2 1 0 2 0 0
 0 0 1 1 0 1 2 1]


In [89]:
from sklearn.metrics import accuracy_score, confusion_matrix

print(accuracy_score(y_test, pred))
print(confusion_matrix(y_test, pred))

0.9777777777777777
[[15  0  0]
 [ 0 15  0]
 [ 0  1 14]]


In [90]:
for k in range(1, 30):
    iris_knn = KNeighborsClassifier(n_neighbors=k)
    iris_knn.fit(X_train, y_train)
    pred = iris_knn.predict(X_test)
    print(k, accuracy_score(y_test, pred))
    # print(confusion_matrix(y_test, pred))
    

1 0.9333333333333333
2 0.9111111111111111
3 0.9555555555555556
4 0.9555555555555556
5 0.9777777777777777
6 0.9555555555555556
7 0.9555555555555556
8 0.9333333333333333
9 0.9555555555555556
10 0.9555555555555556
11 0.9333333333333333
12 0.9333333333333333
13 0.9333333333333333
14 0.9333333333333333
15 0.9555555555555556
16 0.9555555555555556
17 0.9555555555555556
18 0.9555555555555556
19 0.9555555555555556
20 0.9333333333333333
21 0.9555555555555556
22 0.9333333333333333
23 0.9555555555555556
24 0.9333333333333333
25 0.9333333333333333
26 0.9555555555555556
27 0.9333333333333333
28 0.9111111111111111
29 0.9111111111111111


In [91]:
# 과거의 데이터를 기반하여 평균과 표준편차를 구하여 진행하면 전체의 
# 데이터를 충분히 반영하지 못하기 때문에 150개보다 양이 많아야함

x_train, x_test, y_train, y_test = train_test_split(
    iris.data, iris.target,
    stratify=iris.target,
    test_size=0.3,
    random_state=629
)
scaler = StandardScaler()
scaler.fit(x_train)
x_train_std = scaler.transform(x_train)
x_test_std = scaler.transform(x_test)

In [92]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(iris.data)
x_data_std = scaler.transform(iris.data)

x_train, x_test, y_train, y_test = train_test_split(
    x_data_std, iris.target,
    stratify=iris.target,
    test_size=0.3,
    random_state=42,
)

for k in range(1, 30):
    iris_knn = KNeighborsClassifier(n_neighbors=k)
    iris_knn.fit(x_train, y_train)
    pred = iris_knn.predict(x_test)
    print(k, accuracy_score(y_test, pred))


1 0.9333333333333333
2 0.9111111111111111
3 0.9333333333333333
4 0.9111111111111111
5 0.9333333333333333
6 0.9333333333333333
7 0.9333333333333333
8 0.9333333333333333
9 0.9333333333333333
10 0.9333333333333333
11 0.9333333333333333
12 0.9333333333333333
13 0.9333333333333333
14 0.9111111111111111
15 0.9111111111111111
16 0.9333333333333333
17 0.9111111111111111
18 0.9111111111111111
19 0.9111111111111111
20 0.9333333333333333
21 0.9111111111111111
22 0.9111111111111111
23 0.9111111111111111
24 0.8888888888888888
25 0.9111111111111111
26 0.8888888888888888
27 0.8888888888888888
28 0.8666666666666667
29 0.8666666666666667


In [93]:
from sklearn.datasets import load_breast_cancer
bc = load_breast_cancer()
print(bc.DESCR)

.. _breast_cancer_dataset:

Breast cancer Wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

:Number of Instances: 569

:Number of Attributes: 30 numeric, predictive attributes and the class

:Attribute Information:
    - radius (mean of distances from center to points on the perimeter)
    - texture (standard deviation of gray-scale values)
    - perimeter
    - area
    - smoothness (local variation in radius lengths)
    - compactness (perimeter^2 / area - 1.0)
    - concavity (severity of concave portions of the contour)
    - concave points (number of concave portions of the contour)
    - symmetry
    - fractal dimension ("coastline approximation" - 1)

    The mean, standard error, and "worst" or largest (mean of the three
    worst/largest values) of these features were computed for each image,
    resulting in 30 features.  For instance, field 0 is Mean Radius, field
    10 is Radius SE, field 20 is Worst Radius.

    - 