In [5]:
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, confusion_matrix

In [6]:
bc = load_breast_cancer()

X, y = bc.data, bc.target
print(X.shape, y.shape)
print(bc.target_names)

(569, 30) (569,)
['malignant' 'benign']


In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42,
)
print(X_train.shape, X_test.shape)
print(np.unique(y_train, return_counts=True))

(455, 30) (114, 30)
(array([0, 1]), array([170, 285]))


In [10]:
pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("knn", KNeighborsClassifier(n_neighbors=5)),
])

pipe.fit(X_train, y_train)
pred = pipe.predict(X_test)

print(accuracy_score(y_test, pred))
print(confusion_matrix(y_test, pred))

0.956140350877193
[[39  3]
 [ 2 70]]


In [15]:
from sklearn.model_selection import cross_val_score

for k in range(1, 44):
    pipe = Pipeline([
        ("scaler", StandardScaler()),
        ("knn", KNeighborsClassifier(n_neighbors=k)),
    ])
    scores = cross_val_score(pipe, X_train, y_train, cv=5)
    print(k, round(scores.mean(), 4))

1 0.9429
2 0.9538
3 0.9692
4 0.9648
5 0.967
6 0.9692
7 0.9714
8 0.9714
9 0.9692
10 0.9648
11 0.9626
12 0.967
13 0.9582
14 0.967
15 0.9626
16 0.9582
17 0.9582
18 0.9582
19 0.9604
20 0.9604
21 0.9604
22 0.9604
23 0.9582
24 0.956
25 0.9538
26 0.9516
27 0.9538
28 0.9516
29 0.9538
30 0.9538
31 0.9538
32 0.956
33 0.9516
34 0.956
35 0.9516
36 0.9538
37 0.9473
38 0.9516
39 0.9495
40 0.9495
41 0.9473
42 0.9495
43 0.9473


In [16]:
best_k = 7
final = Pipeline([
    ("scaler", StandardScaler()),
    ("knn", KNeighborsClassifier(n_neighbors=best_k)),
])
final.fit(X_train, y_train)
final_pred = final.predict(X_test)

print("최종 정확도:", accuracy_score(y_test, final_pred))
print(confusion_matrix(y_test, final_pred))

최종 정확도: 0.9736842105263158
[[39  3]
 [ 0 72]]


In [17]:
from sklearn.metrics import classification_report

print(classification_report(y_test, final_pred, target_names=bc.target_names))

              precision    recall  f1-score   support

   malignant       1.00      0.93      0.96        42
      benign       0.96      1.00      0.98        72

    accuracy                           0.97       114
   macro avg       0.98      0.96      0.97       114
weighted avg       0.97      0.97      0.97       114

